- deploy/plugins/openkruise/templates/openkruise.yaml
fix(charts): can't find openkruise on charts repo
> fix(charts): can't find openkruise on charts repo

- pkg/service/handlers/registry/registry-hook.go
bugfix for error handle image registry; failed when env annotations is not empty;
```release-note
```
> bugfix; error handle default image registry;

- pkg/service/handlers/environment/handler.go
- pkg/utils/prometheus/log_alert.go
fix #151 
```release-note
fix(log): alert duration in template limit to 10m
```
> 🐞 fix(log): alert duration in template limit to 10m

- deploy/plugins/tke-gpu-manager/templates/tke-gpu-manager.yaml
tke-gpu-manager plugins wrong field
```release-note
fix(plugins): tke-gpu-manager can't regist device if container runtime is containerd
```
> fix(plugin): #155 gpu can't regist device

- pkg/service/handlers/microservice/virtualspace.go
In the past, sort is after paging, fixed.
```release-note
fix(workload): workload list istio-inject sort error.
```
> 🐞 fix(workload): workload list istio-inject sort error

- pkg/service/handlers/cluster/handler.go
- pkg/utils/agents/clientset.go
> 🐞 fix(cluster): apiserver version should from k8s, not db

- pkg/agent/apis/cluster.go
agent log:
```log
2022-07-29 02:51:11.406 error   apis/types.go:19        notok: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
2022/07/29 02:51:11 [Recovery] 2022/07/29 - 02:51:11 panic recovered:
json: unsupported type: map[schema.GroupVersion]error
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.0/render/json.go:58 (0xbcb17d)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.0/context.go:910 (0xc4b0bc)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.0/context.go:953 (0xc4b673)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.0/context.go:204 (0xc45845)
/home/runner/work/kubegems/kubegems/pkg/agent/apis/types.go:29 (0x3a3f944) …
```
> 🐞 fix(apiresource): handle apiresource group failed error

- deploy/plugins/argo-rollouts/templates/rollout-crd-view.yaml
- deploy/plugins/kubegems/templates/kuebgems-crd-view.yaml
- deploy/plugins/kubevela/templates/kubevela-crd-view.yaml
- deploy/plugins/logging/templates/logging-crd-view.yaml
- deploy/plugins/openkruise/templates/openkruise-crd-view.yaml
- deploy/plugins/volume-snapshoter/templates/external-snapshotter-crd-view.yaml
Add the default clusterroles for each plugin ,and associate it to `clusterroles/view`,
add thirdparty crd roles tracked by events
```release-note
add thirdparty crd roles tracked by events
```
> bugfix(id: 178): add thirdparty crd roles tracked by events

- pkg/controller/controllers/environment_controller.go
- pkg/service/handlers/environment/handler.go
- pkg/service/handlers/registry/registry-hook.go
- pkg/service/handlers/registry/synchronizer/imageRegistrySynchronizer.go
- pkg/utils/set/set.go
- pkg/utils/set/set_test.go
- pkg/utils/slice/string.go
bugfix for issue: https://github.com/kubegems/kubegems/issues/181
```release-note
bugfix: environment created after default image registry created lose imagePullSecrets in default serviceAccount
```
> bugfix: imagePullSecrets error

- deploy/plugins/eventer/templates/eventer.yaml
fix eventer log:
{"level":"error","error":"[leases.coordination.k8s.io](http://leases.coordination.k8s.io/) \"[541a35fa.kubegems.io](http://541a35fa.kubegems.io/)\" is forbidden: User \"system:serviceaccount:kubegems-eventer:kubernetes-event-exporter\" cannot get resource \"leases\" in API group \"[coordination.k8s.io](http://coordination.k8s.io/)\" in the namespace \"ingress-nginx-operator-system\"","time":"2022-08-23T11:25:57Z","caller":"/bitnami/blacksmith-sandox/kubernetes-event-exporter-0.11.0/src/[github.com/opsgenie/kubernetes-event-exporter/pkg/kube/watcher.go:84](http://github.com/opsgenie/kubernetes-event-exporter/pkg/kube/watcher.go:84)","message":"Cannot list annotations of the object"}
_What type of changes does your code introduce to KubeGems? Put an `x` in the box that …
> 🐞 fix(eventer): drop 'lease' event

- deploy/plugins/opentelemetry/Chart.yaml
- deploy/plugins/opentelemetry/templates/opentelemetry.yaml
- deploy/plugins/tracing/templates/observability.yaml
- deploy/plugins/tracing/values.yaml
Enable Jaeger SPM to monitor application performace.
Update crd bebore upgrade jaeger-operator plugin.
```
kubectl apply -f https://raw.githubusercontent.com/jaegertracing/jaegeroperator/v1.36.0/config/crd/bases/jaegertracing.io_jaegers.yaml
```
Enable query application performace metrics from jaeger.
```release-note
🚀 Plugins upgrade jaeger-operator-1.36 , opentelemetry-0.58.0
✨ enable Jaeger metrics from prometheus
```
> feat(spm): upgrade jaeger and opentelmetry

- deploy/plugins/nacos/Chart.yaml
- deploy/plugins/nacos/templates/nacos.yaml
Nacos install nacos namespace when plugin enable. the default namespace declared on upstream charts.
```release-note
fixed: nacos install nacos namespace when plugin enable
```
> fix(#222): nacos install default namespace

- deploy/plugins/kubegems-models/plugin.yaml
Fix kubegems plugin been overrided after cluster add.
> fix(plugins): add kubegems plugin by mistake

- deploy/plugins/tracing/Chart.yaml
Jaeger operator doesn't upgrade to 1.36.0 when enable tracing plugin
```release-note
fix: jaeger operator doesn't upgrade to 1.36.0
```
> fix: jaeger plugin doesn't upgrade to 1.36.0

- pkg/service/handlers/cluster/handler.go
- pkg/service/handlers/project/handler_resources.go
- pkg/utils/util.go
get environment resourcequota in concurrency
```release-note
get environment resourcequota in concurrency
```
> enhancement: get environment resourcequota in concurrcy

- pkg/service/handlers/handlers.go
- pkg/service/models/model_cluster.go
- pkg/service/models/validate/base.go
- pkg/service/models/validate/custom_tags.go
- pkg/service/models/validate/custon_validator.go
enhancement for this issue, https://github.com/kubegems/kubegems/issues/280, the installer will use the cluster name as a global value in the helm chart, if use upper case CluserName, will caused downstream error
```release-note
enhancement for https://github.com/kubegems/kubegems/issues/280
```
> enhancement: force validate  clustername ^[a-z][-a-z0-9]{0,32}$

- pkg/service/handlers/cluster/handler.go
- pkg/service/models/model_log.go
condition
for logquery history. user can re use the time range 
```release-note
```
> feature: support logquery history add time_range, user can reuse time

- deploy/plugins/nacos/templates/nacos.yaml
- deploy/plugins/opentelemetry/templates/opentelemetry.yaml
- deploy/plugins/tracing/templates/observability.yaml
- Add jaeger and Nacos custom config on plugins values
- Set the standard label for spanmetrics  https://github.com/kubegems/kubegems/issues/313
```release-note
Set the standard label for spanmetrics
```
> Set the standard label for spanmetrics

- pkg/service/handlers/observability/alert.go
- pkg/service/handlers/observability/channel.go
> 🐞 fix(channel): find alertrule must add 'where', sync map

- pkg/model/store/api/models/api.go
- pkg/model/store/api/models/models.go
- pkg/model/store/repository/models.go
add the api for support upsert model metainfo
```release-note
```
> feature: add the api for support upsert model metainfo

- pkg/edge/server/server.go
```bash
Events:
Type     Reason     Age                From               Message
----     ------     ----               ----               -------
Normal   Scheduled  60s                default-scheduler  Successfully assigned kubegems-edge/kubegems-edge-server-6fc558dd5b-nln46 to k3d-panlq-cluster-agent-0
Normal   Pulled     59s                kubelet            Container image "registry.cn-beijing.aliyuncs.com/kubegems/kubegems:v1.24.5" already present on machine
Normal   Created    59s                kubelet            Created container server
Normal   Started    59s                kubelet            Started container server
Warning  Unhealthy  30s                kubelet            Liveness probe failed: HTTP probe failed with statuscode: 404
Warning  Unhealthy  5s (x10 over 50s) …
```
> fix(edge): edge server lacks the healthz api route
