go.mod
go.sum
pkg/agent/apis/pod.go
pkg/agent/indexer/indexer.go

bugfix pod filter failed

---

pkg/service/handlers/environment/handler.go
pkg/service/handlers/project/handler_resources.go
pkg/service/handlers/tenant/tenant.go
pkg/service/handlers/users/user.go

1. as success when delete environments if crd is not exist
2. when create environment, use current as creator
3. return user with id when  new user created
3. return detail error when create tenant quota

fix some bugs

---

docs/swagger/docs.go
docs/swagger/swagger.json
docs/swagger/swagger.yaml
pkg/agent/apis/apis.go
pkg/agent/apis/loki.go
pkg/controller/controller.go
pkg/controller/webhooks/handler.go
pkg/controller/webhooks/m_tenantgateway.go
pkg/service/handlers/environment/handler.go
pkg/service/handlers/environment/regist.go
pkg/service/handlers/event/event.go
pkg/service/handlers/lokilog/loki.go
pkg/service/handlers/tenant/tenant.go
pkg/service/models/model_tenant.go
pkg/utils/agents/extend.go
pkg/utils/pagination/pagination.go
pkg/utils/prometheus/alert.go
pkg/utils/prometheus/alert_test.go
pkg/utils/util.go
pkg/utils/util_test.go

some feat and bugfix

---

cmd/apps/service.go
pkg/service/handlers/cluster/installer_operator.go
pkg/utils/debug/debug.go
pkg/utils/gemsplugin/installer.go

use repo variable on installer when install cluster

---

pkg/service/models/cache/model_cache.go

bugfix: lost virtualspace cache data

---

pkg/controller/webhooks/m_tenantgateway.go

🎈 perf(gateway): specify different image tag by ingressclass version

---

pkg/service/handlers/noproxy/handler_hpa.go

resolve https://github.com/kubegems/kubegems/issues/87

bugfix: resolve https://github.com/kubegems/kubegems/issues/87

---

Makefile

add BUILD_TAGS env, for condition build

makefile support tags for condition build

---

deploy/plugins/nacos/templates/svc.yaml
pkg/service/handlers/noproxy/handler_hpa.go

1. bugfix for hpa typo
2. feature nacos plugin export service

Feature nacos client

---

pkg/service/models/cache/datas.go

bugfix: fix cache_key error which caused permmission missing

bugfix; environment cache_key error

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

update readme,, contributing, code conduct docs
#130

📃 docs: update readme,, contributing, code conduct docs

---

pkg/controller/webhooks/m_tenantgateway.go

🐞 fix(gateway): use nginx-ingress 2.0.0 on k8s 1.22+

---

deploy/plugins/kubegems/Chart.lock
deploy/plugins/kubegems/Chart.yaml

Signed-off-by: cnfatal <cnfatal@gmail.com>

fix(kubegems): argocd admin password changed after helm upgrade

---

deploy/plugins/logging/templates/kubegems-real-alerting-rules.yaml
deploy/plugins/logging/templates/loki.yaml
deploy/plugins/logging/templates/record-and-alert-rules.yaml
pkg/utils/agents/extend.go
pkg/utils/prometheus/log_alert.go

🐞 fix(loki): useExistingAlertingGroup to replace build-in alertingroups

---

deploy/plugins/opentelemetry/plugin.yaml
deploy/plugins/opentelemetry/templates/opentelemetry.yaml
deploy/plugins/opentelemetry/values.yaml

otlp metrics remotewrite to prometheus

fix(otel): otlp metrics remotewrite to prometheus

---

.github/release.yml

```release-note
Add release.yml to auto generate release note
```

Add release.yml to auto generate release note

---

deploy/plugins/logging/templates/logging-operator-logging.yaml

fix #154 
```release-note
perf(logging): disable tls in logging-operator
```

🎈 perf(logging): disable tls in logging-operator

---

README.md

Correct grammar mistakes

---

deploy/plugins/grafana/templates/grafana.yaml
deploy/plugins/kubegems/templates/ingress.yaml
deploy/plugins/monitoring/templates/kube-prometheus-stack.yaml

perf(ingress): add ingressClass in plugin ingresses
```release-note
perf(ingress): add ingressClass in plugin ingresses
```

🎈 perf(ingress): add ingressClass in plugin ingresses

---

deploy/plugins/kubegems-local/templates/controller/webhook-configuration.yaml

🐞 fix(webhook): ingress api version error

---

deploy/plugins/dcgm-exporter/Chart.lock
deploy/plugins/dcgm-exporter/Chart.yaml
deploy/plugins/dcgm-exporter/plugin.yaml
deploy/plugins/dcgm-exporter/templates/dcgm-exporter.yaml
deploy/plugins/dcgm-exporter/values.yaml

add nvidia dcgm-exporter plugin
```release-note
```

✨ feat(gpu): add nvidia dcgm-exporter plugin

---

deploy/plugins/dcgm-exporter/templates/recording-rule.yaml

add gpu recording rule

---

go.mod
internal/cmd/i18n/main.go
pkg/i18n/generated.go
pkg/i18n/translations.go
pkg/service/handlers/login/login.go
pkg/service/handlers/message/handler.go
translations/en_US/data.json
translations/zh_CN/data.json

support i18n;
```release-note
framework for i18n
```

feature: support i18n

---

pkg/service/aaa/auth/middleware.go
pkg/service/handlers/observability/base.go

🐞 fix(jwt): fix empty jwt payload

---

deploy/plugins/dcgm-exporter/templates/dcgm-exporter.yaml

dcgm-exporter scrape interval to 15s

---

deploy/kubegems-mirror.yaml

a typo fix in kubegems-mirror.yaml
```release-note
a typo fix in kubegems-mirror.yaml
```

fix(deploy): fix typo in kubegems-mirror.yaml

---

pkg/i18n/middleware.go
pkg/i18n/translations.go
pkg/service/aaa/auth/middleware.go
pkg/service/aaa/authorization/perms.go
pkg/service/handlers/login/login.go
pkg/service/routers/router.go

i18n can't recognize language correctly
```release-note
```

bugfix, i18n can't recognize language correctly

---

pkg/agent/apis/prometheus.go

🐞 fix(prometheus): query should not unescape again

---

pkg/service/handlers/observability/metrics.go
pkg/utils/prometheus/promql/promql.go

🎈 perf(metrics): add sumby when query from template

---

pkg/service/handlers/observability/alert.go
pkg/service/handlers/observability/metrics.go
pkg/utils/prometheus/promql/promql.go
pkg/utils/prometheus/promql/promql_test.go

🐞 fix(metrics): label query use full vectorselector expr

---

docs/swagger/docs.go
docs/swagger/swagger.json
docs/swagger/swagger.yaml
pkg/agent/apis/apis.go
pkg/agent/apis/prometheus.go
pkg/service/handlers/observability/base.go
pkg/service/handlers/observability/monitor.go
pkg/utils/agents/extend.go

fix #204 
```release-note
feat(monitor): add monitor collector status api
```

✨ feat(monitor): add monitor collector status api

---

pkg/service/handlers/cluster/handler.go
pkg/service/models/model_cluster.go
pkg/utils/agents/client.go

🎈 perf(cluster): return client cert expire time

---

Dockerfile
config/dashboards/consul.yaml
config/dashboards/container.yaml
config/dashboards/elasticsearch.yaml
config/dashboards/kafka.yaml
config/dashboards/mongodb.yaml
config/dashboards/mysql.yaml
config/dashboards/postgres.yaml
config/dashboards/redis.yaml
deploy/plugins/monitoring/templates/kubegems-default-monitor-promrule.yaml
docs/swagger/docs.go
docs/swagger/swagger.json
docs/swagger/swagger.yaml
pkg/service/handlers/alerts/alerts.go
pkg/service/handlers/observability/base.go
pkg/service/handlers/observability/dashboard.go
pkg/service/handlers/observability/metrics.go
pkg/service/models/base.go
pkg/service/models/model_monitor_dashboard.go
pkg/service/models/model_promql_template.go
pkg/utils/database/helper.go
pkg/utils/prometheus/monitor_alert.go
pkg/utils/prometheus/templates/tpl.go
scripts/generate-system-alert/main.go

feat(dashboard): manage dashboard templates, and import these when init mysql

---

docs/swagger/docs.go
docs/swagger/swagger.json
docs/swagger/swagger.yaml
pkg/service/handlers/oauthserver/oauth.go
pkg/service/handlers/observability/dashboard.go
pkg/service/models/base.go
pkg/service/models/model_user.go
pkg/service/routers/router.go

✨ feat(token): user token manage

---

pkg/controller/controllers/environment_controller.go
pkg/service/handlers/environment/handler.go
pkg/service/handlers/registry/registry-hook.go
pkg/service/handlers/registry/synchronizer/imageRegistrySynchronizer.go
pkg/utils/set/set.go
pkg/utils/set/set_test.go
pkg/utils/slice/string.go

Bugfix image pull secerts error

---

docs/swagger/docs.go
docs/swagger/swagger.json
docs/swagger/swagger.yaml
pkg/service/handlers/announcement/announcement.go
pkg/service/models/base.go
pkg/service/models/model_announcement.go
pkg/service/routers/router.go

✨ feat(announcement): add announcement api

---

deploy/plugins/eventer/templates/eventer.yaml
scripts/release-1.21-update/README.md
scripts/release-1.21-update/exec.sh
scripts/release-1.21-update/main.go

Merge release 1.21.3 back to main
```release-note
```

Merge release 1.21.3

---

config/dashboards/consul.yaml
config/dashboards/container.yaml
config/dashboards/elasticsearch.yaml
config/dashboards/kafka.yaml
config/dashboards/mongodb.yaml
config/dashboards/mysql.yaml
config/dashboards/postgres.yaml
config/dashboards/redis.yaml
docs/swagger/docs.go
docs/swagger/swagger.json
docs/swagger/swagger.yaml
pkg/service/handlers/observability/metrics.go
pkg/service/models/model_monitor_dashboard.go
pkg/utils/gormdatatypes/json_map.go

✨ feat(dashboard): add variables

---

pkg/agent/apis/cluster.go

add api-resources filter

---

deploy/plugins/logging/templates/loki.yaml
deploy/plugins/logging/values.yaml

✨ feat(plugin): logging support aws loki storage

---

go.mod
go.sum
pkg/agent/apis/rest.go
pkg/agent/cluster/cluster.go
pkg/service/handlers/cluster/handler.go
pkg/service/handlers/sels/sels.go
pkg/service/models/cache/model_cache.go

Merge release 1.21 to main

---

pkg/worker/task/cluster_sync.go
pkg/worker/task/tasks.go

🎈 perf(cluster): sync cluster version in worker

---

pkg/service/handlers/cluster/handler.go

Merge release 1.21.6

---

deploy/plugins/eventer/templates/eventer.yaml

🐞 fix(eventer): scale kube client qps

---

config/dashboards/container.yaml
pkg/service/models/model_monitor_dashboard.go

🎈 perf(monitor): container tpl use workload variable, rm uniqindex

---

pkg/service/handlers/environment/handler.go
pkg/service/handlers/observability/metrics.go
pkg/service/handlers/observability/monitor.go
pkg/utils/agents/extend.go
pkg/utils/prometheus/monitor_alert.go

🎈 perf(alert): do not check when delete promql tpl

---

pkg/service/handlers/observability/metrics.go

fix concurrency map write
```release-note
fixed the problem when getting metrics concurrency map to write which caused agent crashed
```

Bufix concurrent map

---

docs/swagger/docs.go
docs/swagger/swagger.json
docs/swagger/swagger.yaml
pkg/agent/apis/cluster.go
pkg/service/handlers/observability/log.go
pkg/service/handlers/observability/monitor.go
pkg/service/handlers/observability/receiver.go
pkg/utils/agents/extend.go
pkg/utils/prometheus/receiver.go
pkg/utils/prometheus/receiver_test.go
pkg/utils/prometheus/types.go
scripts/generate-system-alert/main.go
scripts/release-1.20.0-beta.2-update/main.go
scripts/release-1.21-update/main.go

Merge log monitor receiver

---

pkg/agent/apis/apis.go
pkg/agent/apis/debug.go
pkg/agent/apis/pod.go
pkg/agent/apis/tools.go
pkg/agent/ws/readme.txt
pkg/agent/ws/websocket.go
pkg/service/handlers/proxy/proxy.go

feature add, support download file from container; related issue https://github.com/kubegems/kubegems/issues/169
```release-note
support download file from container
```

feature: support download/upload file from container

---

go.mod
pkg/service/models/base.go
pkg/utils/database/database.go

add collation options for databse connection
```release-note
add collation options for databse connection
```

change database default collation. for support emoji

---

deploy/plugins/kubegems-models/Chart.yaml
deploy/plugins/kubegems-models/README.md
deploy/plugins/kubegems-models/plugin.yaml
deploy/plugins/kubegems-models/templates/_helpers.tpl
deploy/plugins/kubegems-models/templates/store/deployment.yaml
deploy/plugins/kubegems-models/templates/store/service.yaml
deploy/plugins/kubegems-models/templates/sync/deployment.yaml
deploy/plugins/kubegems-models/templates/sync/service.yaml
deploy/plugins/kubegems-models/values.schema.json
deploy/plugins/kubegems-models/values.yaml

fix(models): cherry-pick from main

---

README.md
README_zh.md

docs: add contributors on readme

---

pkg/utils/harbor/harbor.go

fix(image): parse harbor repo with sub project

---

README.md
README_zh.md

Revert "docs: add contributors on readme"

---

docs/swagger/docs.go
docs/swagger/swagger.json
docs/swagger/swagger.yaml
pkg/agent/apis/alert.go
pkg/agent/apis/pod.go
pkg/utils/prometheus/receiver.go

✨ feat(receiver): add alert proxy receiver for feishu

---

deploy/plugins/monitoring/files/alertproxy.yaml
deploy/plugins/monitoring/templates/_helpers.tpl
deploy/plugins/monitoring/templates/alertproxy.yaml
deploy/plugins/monitoring/values.yaml
pkg/utils/prometheus/receiver.go

✨ feat(monitor): monitor plugin add alertproxy component

---

deploy/plugins/seldon/Chart.lock
deploy/plugins/seldon/Chart.yaml
deploy/plugins/seldon/plugin.yaml
deploy/plugins/seldon/templates/seldon-core-operator.yaml
deploy/plugins/seldon/values.yaml
pkg/model/deployment/modelseldon.go
pkg/model/store/api/modeldeployments/modeldeployment.go

fix models controller

---

deploy/installer.yaml
deploy/plugins/kubegems-models/crds/models.kubegems.io_modeldeployments.yaml
pkg/apis/models/v1beta1/types.go
pkg/model/deployment/modelseldon.go
pkg/model/store/api/modeldeployments/modeldeployment.go
pkg/model/store/api/models/admin.go
pkg/model/store/api/models/sources.go
pkg/model/store/repository/models.go
pkg/model/store/repository/types.go

perf(model): add model annotations

---

deploy/plugins/kubegems-models/crds/models.kubegems.io_modeldeployments.yaml
deploy/plugins/seldon/templates/seldon-core-operator.yaml
pkg/apis/models/v1beta1/types.go
pkg/model/deployment/modelseldon.go

feat(models): support for modelDeployment recreate

---

docs/swagger/docs.go
docs/swagger/swagger.json
docs/swagger/swagger.yaml
pkg/msgbus/switcher/alert.go
pkg/msgbus/switcher/switch.go
pkg/service/handlers/observability/base.go
pkg/service/handlers/observability/channel.go
pkg/utils/prometheus/alert.go
pkg/utils/prometheus/channels/channel.go
pkg/utils/prometheus/channels/email.go
pkg/utils/prometheus/channels/feishu.go
pkg/utils/prometheus/channels/webhook.go

Feat channel test api

---

pkg/service/handlers/users/regist.go
pkg/service/handlers/users/user.go
pkg/service/models/base.go
pkg/service/models/kubeclient.go
pkg/service/models/model_config.go
pkg/service/models/model_environment.go
pkg/service/models/model_log.go
pkg/service/models/model_logging.go
pkg/service/models/model_message.go
pkg/service/models/model_promql_template.go
pkg/service/models/model_registry.go

Revert "Bugfix user related"

---

deploy/plugins/monitoring/files/alertproxy.yaml
deploy/plugins/monitoring/values.yaml

🎈 perf(monitot): upgrade alertproxy from v0.1.0 to v0.2.0

---

pkg/service/handlers/observability/alert.go

🦄 refactor(alert):alert overview use created_at rather than starts_at

---

config/dashboards/container.yaml
scripts/release-1.22-update/README.md

🐞 fix(dashborad): tpl contaienr memory error

---

pkg/service/observe/log_alert.go
pkg/service/observe/log_alert_test.go

🐞 fix(logql): regex content use " ` "

---

deploy/plugins/monitoring/files/alertproxy.yaml
deploy/plugins/monitoring/values.yaml

upgrade alertproxy to v0.3.0

---

pkg/utils/prometheus/channels/aliyunmsg.go
pkg/utils/prometheus/channels/aliyunvoice.go
pkg/utils/prometheus/channels/channel.go
pkg/utils/prometheus/channels/email.go
pkg/utils/prometheus/channels/webhook.go
pkg/utils/util.go
pkg/utils/util_test.go

merge this after 1.22 released.
```release-note
```

Feat aliyun channels

---

.gitignore
pkg/service/observe/alert.go
pkg/utils/prometheus/channels/channel.go
pkg/utils/prometheus/channels/email.go
pkg/utils/prometheus/channels/feishu.go
pkg/utils/prometheus/channels/webhook.go
scripts/release-1.22-update/main.go

🎈 perf(alert): receiver channel set status

---

deploy/plugins/nacos/values.yaml
deploy/plugins/tracing/values.yaml

Adding missing variables

---

pkg/service/observe/alert.go
pkg/service/observe/log_alert.go
pkg/service/observe/monitor_alert.go

🐞 fix(receiver): do not re-gen receiver when delete

---

deploy/plugins/tracing/templates/observability.yaml

fix jaeger helm index error

---

.gitignore
CHANGELOG.md
README.md
README_zh.md
deploy/installer.yaml
deploy/kubegems.yaml
pkg/service/handlers/observability/metrics.go
pkg/service/models/model_promql_template.go
pkg/service/observe/alert.go
pkg/service/observe/client.go
pkg/service/observe/log_alert.go
pkg/service/observe/monitor_alert.go
pkg/utils/argo/mixedclient.go
pkg/utils/prometheus/channels/channel.go
pkg/utils/prometheus/channels/email.go
pkg/utils/prometheus/channels/feishu.go
pkg/utils/prometheus/channels/webhook.go
scripts/release-1.22-update/main.go

Merge 1.22.1

---

cmd/apps/service.go
docs/swagger/docs.go
docs/swagger/swagger.json
docs/swagger/swagger.yaml
pkg/service/handlers/observability/base.go
pkg/service/handlers/observability/dashboard.go
pkg/service/handlers/observability/metrics.go
pkg/service/handlers/users/user.go
pkg/service/models/model_promql_template.go
pkg/utils/agents/extend.go
pkg/utils/debug/debug.go
pkg/utils/prometheus/graph.go
pkg/utils/prometheus/promql/promql.go
pkg/utils/prometheus/promql/promql_test.go
scripts/release-1.23-update/main.go

Feat dashboard muti query targets

---

pkg/service/models/model_alert_channel.go
pkg/utils/prometheus/channels/channel.go
pkg/utils/prometheus/channels/email.go
pkg/utils/prometheus/channels/feishu.go
pkg/utils/prometheus/channels/webhook.go
pkg/utils/util.go
scripts/release-1.22-update/main.go

✨ feat(channel): add sendResolved option

---

pkg/service/aaa/auth/middleware.go

🐞 fix(auth): user auth error print log

---

docs/swagger/docs.go
docs/swagger/swagger.json
docs/swagger/swagger.yaml
pkg/apis/gems/common.go
pkg/service/handlers/observability/base.go
pkg/service/handlers/observability/metrics.go
pkg/service/observe/client.go
pkg/service/observe/jaeger.go
pkg/utils/agents/extend.go
pkg/utils/prometheus/promql/promql.go
pkg/utils/prometheus/promql/promql_test.go
pkg/utils/prometheus/util.go

✨ feat(otel): add otel service appmonitor apis

---

docs/swagger/docs.go
docs/swagger/swagger.json
docs/swagger/swagger.yaml
pkg/service/handlers/tenant/regist.go
pkg/service/handlers/tenant/tenant.go

✨ feat(env): search environment

---

go.mod
go.sum
pkg/service/routers/router.go
pkg/utils/otel/gin.go
pkg/utils/otel/runtime.go

add otel runtime metric

---

pkg/utils/prometheus/channels/channel.go
pkg/utils/prometheus/channels/dingding.go

✨ feat(channel): dingding

---

docs/swagger/docs.go
docs/swagger/swagger.json
docs/swagger/swagger.yaml
pkg/service/handlers/observability/alert.go
pkg/service/handlers/observability/channel.go
pkg/service/handlers/observability/log.go
pkg/service/handlers/observability/monitor.go
pkg/service/models/base.go
pkg/service/models/model_alert_channel.go
pkg/service/models/model_alert_rule.go
pkg/service/models/types.go
pkg/utils/prometheus/promql/label.go
pkg/utils/util.go

#329 #359 
```release-note
```

Refactor alert rule

---

docs/swagger/docs.go
docs/swagger/swagger.json
docs/swagger/swagger.yaml
pkg/service/handlers/observability/alert.go
pkg/service/handlers/observability/log.go
pkg/service/handlers/observability/monitor.go
pkg/service/models/model_alert_rule.go
pkg/utils/workflow/server.go
pkg/worker/task/alertrule_sync.go
pkg/worker/task/tasks.go

✨ feat(worker): add task to sync alert rule state and check config

---

pkg/worker/task/alertrule_sync.go

close #382 
```release-note
```

🎈 perf(worker): check alertrule query result

---

config/dashboards/consul.yaml
config/dashboards/container.yaml
config/dashboards/elasticsearch.yaml
config/dashboards/kafka.yaml
config/dashboards/mongodb.yaml
config/dashboards/mysql.yaml
config/dashboards/otel_http.yaml
config/dashboards/otel_jvm.yaml
config/dashboards/otel_jvm_old.yaml
config/dashboards/postgres.yaml
config/dashboards/redis.yaml
config/promql_tpl.yaml
pkg/service/handlers/observability/alert.go
scripts/export-monitor-tpls/main.go
scripts/release-1.23-update/main.go

Export monitor tpls

---

pkg/agent/apis/alert.go
pkg/agent/apis/watch.go

bugfix for this one ,https://github.com/kubegems/kubegems/issues/387
```release-note
```

bugfix, websocket caused memory grow high

---

pkg/service/handlers/project/handler_project.go

BUGFIX for modify user project role failed
```release-note
```

BUGFIX for modify user project role failed

---

pkg/log/log.go

fix zap log lost, but may take affect to performance.
ref: https://github.com/uber-go/zap/issues/588
```release-note
```

disable zap logger sampling

---

CHANGELOG.md
README.md
README_zh.md
deploy/installer.yaml
deploy/kubegems.yaml

Prepare v1.23

---

pkg/service/handlers/observability/alert.go
pkg/service/models/model_alert_rule.go
pkg/service/observe/client.go
scripts/release-1.23-update/README.md
scripts/release-1.23-update/migrate-alertrule.go

🎈 perf(script): check alertrule name on 1.23 update

---

pkg/msgbus/api/server.go
pkg/service/aaa/auth/middleware.go
pkg/service/apis/apis.go
pkg/service/routers/router.go
pkg/utils/agents/client.go
pkg/utils/agents/clientset.go
pkg/utils/agents/http-websocket.go
pkg/utils/agents/typed.go
pkg/utils/otel/gin/gintrace.go
pkg/utils/otel/otel.go

🎈 perf(otel): use baggage

---

pkg/service/aaa/auth/middleware.go
pkg/service/handlers/oauthserver/oauth.go
pkg/service/routers/router.go

🐞 fix(oauth): add tracer

---

go.mod
go.sum
pkg/service/handlers/tenant/tenant.go

1. upgrade configer  v1.1.4; for support sync configdatas
2. bugfix npe error when delete tenant members
```release-note
```

bugfix npe & upgrade configer

---

pkg/service/handlers/tenant/tenant.go

after delete tenant member,do log audit event, nil pointer error when get the tenant name 
```release-note
```

bugfix audit npe when delete tenant member

---

pkg/service/handlers/observability/metrics.go

🐞 fix(appmonitor): otel overview ignore nan

---

pkg/service/handlers/observability/alert.go
pkg/service/observe/client.go
pkg/utils/prometheus/channels/email.go

when ExecuteInEachCluster, umarshal will range and write this map concurrently.
```release-note
```

🐞 fix(alertrule): email secret label shouldn't use globa variable map.

---

pkg/service/handlers/observability/alert.go
pkg/service/models/types.go
pkg/utils/clusterinfo/clusterinfo.go
scripts/release-1.23-update/main.go
scripts/release-1.23-update/migrate-alertrule.go

🎈 perf(alert): remove alertlevel value if from promql or logql

---

CHANGELOG.md
Dockerfile.kubectl
config/system_alert.yaml
deploy/installer.yaml
deploy/kubegems.yaml
pkg/service/handlers/application/manifest_files.go
pkg/service/handlers/observability/alert.go
pkg/service/models/types.go
pkg/service/observe/client.go
pkg/utils/clusterinfo/clusterinfo.go
pkg/utils/prometheus/channels/email.go
pkg/worker/task/alertrule_sync.go
scripts/release-1.23-update/main.go
scripts/release-1.23-update/migrate-alertrule.go
tools/helm-schema/main.go

merge for v1.23.5

---

CHANGELOG.md
config/system_alert.yaml
deploy/installer.yaml
deploy/kubegems.yaml
pkg/service/handlers/application/processor_deploy.go
pkg/service/handlers/cluster/handler.go
pkg/service/handlers/handlers.go
pkg/service/handlers/observability/alert.go
pkg/service/models/model_alert_rule.go
pkg/utils/agents/client.go
pkg/worker/task/cluster_sync.go

merge for v1.23.6

---

pkg/service/handlers/proxy/websocket.go

add heartbeat

---

pkg/edge/server/api_cluster.go
pkg/service/aaa/audit/audit.go
pkg/utils/system/listen.go

```bash
runtime: goroutine stack exceeds 1000000000-byte limit
runtime: sp=0x14023060390 stack=[0x14023060000, 0x14043060000]
fatal error: stack overflow
```

fix(edge): httphandler is stuck in infinite loop 
